### PR TITLE
Update pipeline to DSL2

### PR DESCRIPTION
**Pull request by Valiec**
Just a small PR updating the Nextflow to DSL2. Still in progress, I haven't tested it, don't merge yet. 

I wanted to do this mostly because the recall_pangolin pipeline that's in progress on the pangolin branch is already DSL2, plus this is another leftover feature branch I have open.

### CODE REVIEW

**Comment by Valiec** [comment]
I've test-run this (without DB load) and it worked, so I'd say it seems ready.

**Comment by Valiec** [comment]
Update: I'm putting a change to DSL2 into the pangolin branch as well, along with a good number of other pipeline changes, so maybe this should wait until that PR?

**Comment by bwlang** [comment]
ok - i'll wait for the updates.

**Comment by Valiec** [comment]
I've incorporated these changes into #88, closing.

**Pull request closed without merging**
