### PR TITLE
Set Nextflow to use Mamba & and store Pangolin version

### PR DESCRIPTION
**Pull request by Valiec**
Sets Nextflow to use mamba instead of conda for installing conda packages (known working, I hotfixed it days ago), _and_ stores the pangolin version in the table (untested).

### CODE REVIEW

**Comment by Valiec** [comment]
It's worked for the last few days with this setting in place.

**Comment by Valiec** [comment]
Oops, I forgot there was still a PR open on this branch. As these are both small changes, maybe we should combine them?

**Comment by Valiec** [comment]
Made the title accurate. If you would prefer splitting these changes, I can close this PR and split them though.

**Review by bwlang — APPROVED** [review]
looks great!

**Pull request merged**
